name: Automated push Docker image to Docker Hub

on: 
  push:
    branches: ["v1", "main"]
  pull_request:
    branches: ["v1", "main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: Florstrd/DevOps-Project

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker-compose build --no-cache --force-rm
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Docker image
        run: docker-compose up -d
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-actions@v2

    - name: Login to Docker Hub
      uses: docker/login-actions@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-actions@v3
      with: 
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Buid and push image
      uses: docker/build-push-action@v2
      with: 
        context: "{{defaultContext}}"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
